stock_list:
  # 주식 (티커 번호 정렬)
  - ["000270", "KR"]  # 기아
  - ["000370", "KR"]  # 한화손해보험
  - ["000660", "KR"]  # SK하이닉스
  - ["001440", "KR"]  # 대한전선
  - ["001450", "KR"]  # 현대해상
  - ["005830", "KR"]  # DB손해보험
  - ["005387", "KR"]  # 현대차2우B
  - ["005930", "KR"]  # 삼성전자
  - ["005935", "KR"]  # 삼성전자우
  - ["005940", "KR"]  # NH투자증권
  # - ["00680K", "KR"]  # 미래에셋증권2우B - 잘못된 코드
  - ["006800", "KR"]  # 미래에셋증권
  - ["007660", "KR"]  # 이수페타시스
  - ["009830", "KR"]  # 한화솔루션
  - ["010140", "KR"]  # 삼성중공업
  - ["010950", "KR"]  # S-OIL
  - ["010955", "KR"]  # S-Oil우
  - ["011070", "KR"]  # LG이노텍
  - ["016360", "KR"]  # 삼성증권
  - ["017670", "KR"]  # SK텔레콤
  - ["024110", "KR"]  # 기업은행
  - ["029780", "KR"]  # 삼성카드
  - ["030200", "KR"]  # KT
  - ["032640", "KR"]  # LG유플러스
  - ["032830", "KR"]  # 삼성생명
  - ["033640", "KR"]  # 네패스
  - ["033780", "KR"]  # KT&G
  - ["035420", "KR"]  # NAVER
  - ["035720", "KR"]  # 카카오
  - ["035900", "KR"]  # JYP Ent.
  - ["036540", "KR"]  # SFA반도체
  - ["042670", "KR"]  # HD현대인프라코어
  - ["055550", "KR"]  # 신한지주
  - ["066570", "KR"]  # LG전자
  - ["067310", "KR"]  # 하나마이크론
  - ["069620", "KR"]  # 대웅제약
  - ["078930", "KR"]  # GS
  - ["085620", "KR"]  # 미래에셋생명
  - ["086790", "KR"]  # 하나금융지주
  - ["088350", "KR"]  # 한화생명
  - ["105560", "KR"]  # KB금융
  - ["138040", "KR"]  # 메리츠금융지주
  - ["139130", "KR"]  # iM금융지주
  - ["248070", "KR"]  # 솔루엠
  - ["267250", "KR"]  # HD현대
  - ["267270", "KR"]  # HD현대건설기계
  - ["271560", "KR"]  # 오리온
  - ["272210", "KR"]  # 한화시스템
  - ["294090", "KR"]  # 이오플로우
  - ["316140", "KR"]  # 우리금융지주
  - ["323410", "KR"]  # 카카오뱅크
  - ["344820", "KR"]  # KCC글라스
  - ["365340", "KR"]  # 성일하이텍
  - ["365550", "KR"]  # ESR켄달스퀘어리츠
  - ["373220", "KR"]  # LG에너지솔루션
  - ["403870", "KR"]  # HPSP
  - ["452260", "KR"]  # 한화갤러리아
  - ["293940", "KR"]  # 신한알파리츠
  - [ "330590", "KR" ]  # 롯데리츠
  - [ "348950", "KR" ]  # 제이알글로벌리츠
  - [ "395400", "KR" ]  # SK리츠
  - [ "432320", "KR" ]  # KB스타리츠

  # ETF (티커 번호 정렬)
  - ["088980", "KR"]  # 맥쿼리인프라
  - ["091170", "KR"]  # KODEX 은행
  - ["091180", "KR"]  # KODEX 자동차
  - ["091230", "KR"]  # TIGER 반도체
  - ["139220", "KR"]  # TIGER 200 건설
  - ["153130", "KR"]  # KODEX 단기채권
  - ["161510", "KR"]  # PLUS 고배당주
  - ["214980", "KR"]  # KODEX 단기채권PLUS
  - ["219480", "KR"]  # KODEX 미국S&P500선물(H)
  - ["228790", "KR"]  # TIGER 화장품
  - ["244580", "KR"]  # KODEX 바이오
  - ["261240", "KR"]  # KODEX 미국달러선물
  - ["294400", "KR"]  # KOSEF 200TR
  - ["304660", "KR"]  # KODEX 미국30년국채울트라선물(H)
  - ["305540", "KR"]  # TIGER 2차전지테마
  - ["305720", "KR"]  # KODEX 2차전지산업
  - ["308620", "KR"]  # KODEX 미국채10년선물
  - ["314250", "KR"]  # KODEX 미국빅테크10(H)
  - ["319640", "KR"]  # TIGER 골드선물(H)
  - ["325020", "KR"]  # KODEX 배당가치
  - ["329200", "KR"]  # TIGER 리츠부동산인프라
  - ["354350", "KR"]  # HANARO 글로벌럭셔리S&P(합성)
  - ["357870", "KR"]  # TIGER CD금리투자KIS(합성)
  - ["360200", "KR"]  # ACE 미국S&P500
  - ["364970", "KR"]  # TIGER 바이오TOP10
  - ["364980", "KR"]  # TIGER 2차전지TOP10
  - ["368590", "KR"]  # RISE 미국나스닥100
  - ["371160", "KR"]  # TIGER 차이나항셍테크
  - ["371460", "KR"]  # TIGER 차이나전기차SOLACTIVE
  - ["379780", "KR"]  # RISE 미국S&P500
  - ["381170", "KR"]  # TIGER 미국테크TOP10 INDXX
  - ["381180", "KR"]  # TIGER 미국필라델피아반도체나스닥
  - ["385540", "KR"]  # RISE 종합채권(A-이상)액티브
  - ["390390", "KR"]  # KODEX 미국반도체MV
  - ["395290", "KR"]  # HANARO Fn K-POP&미디어
  - ["429000", "KR"]  # TIGER 미국S&P500배당귀족
  - ["433980", "KR"]  # KODEX TDF2040액티브
  - ["434730", "KR"]  # HANARO 원자력iSelect
  - ["436140", "KR"]  # SOL 종합채권(AA-이상)액티브
  - ["438560", "KR"]  # SOL 국고채3년
  - ["440910", "KR"]  # WON 미국우주항공방산
  - ["442320", "KR"]  # RISE 글로벌원자력
  - ["446720", "KR"]  # SOL 미국배당다우존스
  - ["448290", "KR"]  # TIGER 미국S&P500TR(H)
  - ["448300", "KR"]  # TIGER 미국나스닥100TR(H)
  - ["449450", "KR"]  # PLUS K방산
  - ["452360", "KR"]  # SOL 미국배당다우존스(H)
  - ["453810", "KR"]  # KODEX 인도Nifty50
  - ["453850", "KR"]  # ACE 미국30년국채액티브(H)
  - ["456880", "KR"]  # ACE 미국달러SOFR금리(합성)
  - ["457480", "KR"]  # ACE 테슬라밸류체인액티브
  - ["458730", "KR"]  # TIGER 미국배당다우존스
  - ["458760", "KR"]  # TIGER 미국배당다우존스타겟커버드콜2호
  - ["461260", "KR"]  # ACE 25-06 회사채(AA-이상)액티브
  - ["461270", "KR"]  # ACE 26-16 회사채(AA-이상)액티브
  - ["464310", "KR"]  # TIGER 글로벌AI&로보틱스 INDXX
  - ["465580", "KR"]  # ACE 미국빅테크TOP7 Plus
  - ["465680", "KR"]  # KODEX 24-12 은행채(AA+이상)액티브
  - ["466920", "KR"]  # SOL 조선TOP3플러스
  - ["469830", "KR"]  # SOL 초단기채권액티브
  - ["476800", "KR"]  # KODEX 한국부동산리츠인프라
  - ["481190", "KR"]  # SOL 미국테크TOP10
  - ["482730", "KR"]  # TIGER 미국S&P500타겟데일리커버드콜
  - ["486450", "KR"]  # SOL 미국AI전력인프라
  - ["487230", "KR"]  # KODEX 미국AI전력핵심인프라
  - ["487240", "KR"]  # KODEX AI전력핵심설비
  - ["488500", "KR"]  # TIGER 미국S&P500동일가중
  - ["489250", "KR"]  # KODEX 미국배당다우존스
  - ["494670", "KR"]  # TIGER 조선TOP10
  - ["497780", "KR"]  # KoAct 미국천연가스인프라액티브
  - ["498270", "KR"]  # KOSEF 미국양자컴퓨팅

  # 미국 주식 - 보유 종목 (섹터별 분류)
  
  # 기술주 (Big Tech & Software)
  - ["AAPL", "US"]    # Apple Inc.
  - ["GOOGL", "US"]   # Alphabet Inc. (Google)
  - ["NVDA", "US"]    # NVIDIA Corporation
  - ["AMZN", "US"]    # Amazon.com Inc.
  - ["CRM", "US"]     # Salesforce Inc.
  - ["AMD", "US"]     # Advanced Micro Devices
  - ["ARM", "US"]     # Arm Holdings
  - ["QCOM", "US"]    # Qualcomm Inc.
  - ["AVGO", "US"]    # Broadcom Inc.
  - ["PLTR", "US"]    # Palantir Technologies
  - ["ANET", "US"]    # Arista Networks
  - ["BBAI", "US"]    # BigBear.ai Holdings
  - ["MU", "US"]      # Micron Technology
  - ["MRVL", "US"]    # Marvell Technology
  - ["CSCO", "US"]    # Cisco Systems

  # 전기차 & 에너지
  - ["TSLA", "US"]    # Tesla Inc.
  - ["PCG", "US"]     # PG&E Corporation
  - ["XOM", "US"]     # Exxon Mobil
  - ["OXY", "US"]     # Occidental Petroleum
  - ["CVX", "US"]     # Chevron Corporation
  - ["NEE", "US"]     # NextEra Energy

  # 헬스케어 & 제약
  - ["NVO", "US"]     # Novo Nordisk
  - ["CVS", "US"]     # CVS Health Corporation
  - ["JNJ", "US"]     # Johnson & Johnson
  - ["PFE", "US"]     # Pfizer Inc.

  # 소비재 & 리테일
  - ["NKE", "US"]     # Nike Inc.
  - ["MCD", "US"]     # McDonald's Corporation
  - ["PEP", "US"]     # PepsiCo Inc.
  - ["KO", "US"]      # The Coca-Cola Company
  - ["SBUX", "US"]    # Starbucks Corporation
  - ["KR", "US"]      # The Kroger Co.
  - ["KHC", "US"]     # The Kraft Heinz Company
  - ["PG", "US"]      # Procter & Gamble

  # 금융 & 은행
  - ["BAC", "US"]     # Bank of America
  - ["C", "US"]       # Citigroup Inc.
  - ["WFC", "US"]     # Wells Fargo & Company
  - ["AIG", "US"]     # American International Group
  - ["ALLY", "US"]    # Ally Financial Inc.
  - ["BAC-P", "US"]   # Bank of America Preferred
  - ["COF-N", "US"]   # Capital One Financial Preferred

  # 통신
  - ["VZ", "US"]      # Verizon Communications
  - ["CMCSA", "US"]   # Comcast Corporation
  - ["T", "US"]       # AT&T Inc.

  # 산업재 & 제조업
  - ["VRT", "US"]     # Vertiv Holdings
  - ["HRL", "US"]     # Hormel Foods Corporation
  - ["HPQ", "US"]     # HP Inc.

  # 리츠 (REITs)
  - ["O", "US"]       # Realty Income Corporation
  - ["OHI", "US"]     # Omega Healthcare Investors
  - ["IIPR", "US"]    # Innovative Industrial Properties
  - ["STAG", "US"]    # STAG Industrial
  - ["ADC", "US"]     # Agree Realty Corporation

  # BDC & 고배당주
  - ["ARCC", "US"]    # Ares Capital Corporation
  - ["MAIN", "US"]    # Main Street Capital
  - ["HTGC", "US"]    # Hercules Capital
  - ["BXSL", "US"]    # Blackstone Secured Lending Fund

  # 기타 특수 종목
  - ["NU", "US"]      # Nu Holdings Ltd.
  - ["VST", "US"]     # Vistra Corp.
  - ["FORM", "US"]    # FormFactor Inc.
  - ["SMR", "US"]     # NuScale Power Corporation
  - ["TEM", "US"]     # Tempus AI Inc.
  - ["APLE", "US"]    # Apple Hospitality REIT
  - ["GOF", "US"]     # Guggenheim Strategic Opportunities Fund
  - ["MO", "US"]      # Altria Group Inc.
  - ["BTI", "US"]     # British American Tobacco
  - ["PDI", "US"]     # PIMCO Dynamic Income Fund
  - ["BHFAM", "US"]   # Brighthouse Financial
  - ["WBTN", "US"]    # Webtoon Entertainment
  - ["MITT-A", "US"]  # AG Mortgage Investment Trust Preferred

  # 미국 ETF (추가) - 채권 ETF
  - ["TLT", "US"]     # iShares 20+ Year Treasury Bond ETF (장기 국채)
  - ["IEF", "US"]     # iShares 7-10 Year Treasury Bond ETF (중기 국채)
  - ["SGOV", "US"]    # iShares 0-3 Month Treasury Bond ETF (초단기 국채)
  
  # 미국 ETF - 주식형 ETF
  - ["QQQM", "US"]    # Invesco NASDAQ 100 ETF
  - ["SPLG", "US"]    # SPDR Portfolio S&P 500 ETF
  
  # 미국 ETF - 배당/인컴 ETF
  - ["SCHD", "US"]    # Schwab US Dividend Equity ETF
  - ["JEPI", "US"]    # JPMorgan Equity Premium Income ETF
  - ["JEPQ", "US"]    # JPMorgan Nasdaq Equity Premium Income ETF
  - ["DIVO", "US"]    # Amplify CWP Enhanced Dividend Income ETF
  
  # 미국 ETF - 섹터 ETF (SPDR Select Sector)
  - ["XLU", "US"]     # Utilities Select Sector SPDR Fund (유틸리티)
  - ["XLE", "US"]     # Energy Select Sector SPDR Fund (에너지)
  - ["XLB", "US"]     # Materials Select Sector SPDR Fund (소재)
  - ["XLRE", "US"]    # Real Estate Select Sector SPDR Fund (부동산)
  - ["XLF", "US"]     # Financial Select Sector SPDR Fund (금융)
  - ["XLC", "US"]     # Communication Services Select Sector SPDR Fund (통신)
  
  # 미국 ETF - 테마/대체자산 ETF
  - ["CIBR", "US"]    # First Trust NASDAQ Cybersecurity ETF (사이버보안)
  - ["VNQ", "US"]     # Vanguard Real Estate ETF (리츠)
  - ["IAU", "US"]     # iShares Gold Trust (금)


# ------------------------------
# 아래는 스트레스 테스트용 설정(계획 단계) 예시입니다.
# 실제 실행 코드는 본 이슈 범위에 포함되지 않으며, 값은 문서 합의 후 조정됩니다.
# ------------------------------

# 부하 프로파일(예시)
load_profile:
  target_rps: 15          # 지속 목표 rps (한국투자 API 20rps 대비 보수적)
  ramp_up_sec: 30         # 램프업 시간(초)
  sustain_sec: 240        # 유지 시간(초)
  ramp_down_sec: 30       # 램프다운(초)
  max_concurrency: 200    # 동시 작업 상한(힌트)

# 레이트 제한 가드(예시)
rate_limit_guard:
  global_rps_cap: 18      # 절대 상한 rps(버퍼 포함)
  burst_size: 5           # 짧은 버스트 허용치
  retry:
    max_attempts: 3
    backoff: exponential  # 고정/선형/지수 등 선택 가능
    base_delay_ms: 100
    jitter_ms: [50, 150]  # 지터 범위(ms)

# 시나리오 선택/설정(예시)
scenario:
  enable:
    - S1   # 단일 종목 고빈도
    - S2   # 다종목 선형 스케일
    - S3   # 버스트 혼합
    - S4   # 캐시 히트/미스 비교
  s1:
    tickers:  ["005930:KR", "AAPL:US"]
    duration_sec: 300
  s2:
    use_all: true
    duration_sec: 300
  s3:
    burst_rps: 30
    burst_sec: 30
    cool_rps: 12
    cool_sec: 180
    cycles: 5
  s4:
    cache_hit_ratio_target: 0.8

# 리포팅(예시)
reporting:
  out_dir: ./stress
  formats: [csv, html]
